### ISSUE TITLE
MEDUSA merge prevents GLOBAL_QCO building

### ISSUE THREAD

**Issue by atb299** [NOC-MSM/NOC_Near_Present_Day#24] opened 2024-01-17 21:55 UTC
File cfgs/work_cfgs.txt needs changing to ensure that both GLOBAL_QCO and GLOBAL_QCO_MEDUSA are built. Even doing this, it appears that some of MEDUSA is getting picked up by the GLOBAL_QCO build:

find: 'TOP/MEDUSA': No such file or directory

/tmp/ifortsPmUKL.i90(144): error #6580: Name in only-list does not exist or is not accessible.   [MED_DIAG]
      USE trcwri_medusa,     ONLY: med_diag
-----------------------------------^
/tmp/ifortsPmUKL.i90(693): error #6404: This name does not have a type, and must have an explicit type.   [MED_DIAG]
               IF( med_diag%REMINN .OR. med_diag%REMINN1 ) THEN
-------------------^
...
/tmp/ifort1ZnmJq.i90(853): error #6341: A logical data type is required in this context.   [BDDTDISI3]
            IF( med_diag%BDDTDISI3 ) bddtdisi3(ji,jj,jk) =  btra(ji,jj,jpmsil)
-------------------------^
compilation aborted for /dssgfs01/scratch/atb299/NOC_NPD/20240115/NOC_Near_Present_Day/nemo/cfgs/GLOBAL_QCO/BLD/ppsrc/nemo/btd_update.f90 (code 1)
fcm_internal compile failed (256)
gmake: *** [btd_update_mod.o] Error 1
gmake -f /dssgfs01/scratch/atb299/NOC_NPD/20240115/NOC_Near_Present_Day/nemo/cfgs/GLOBAL_QCO/BLD/Makefile -j 32 all failed (2) at /dssgfs01/scratch/atb299/NOC_NPD/20240115/NOC_Near_Present_Day/nemo/ext/FCM/bin/../lib/Fcm/Build.pm line 597.

**Comment by jupalm** [comment] 2024-02-14 16:57
Ah?! I didn't see that! 
Is it still a problem ? or should it be an action on me ?

Julien.

**Comment by jupalm** [comment] 2024-02-15 12:06
Well, i've just tried, and it does compile...

The secret is to not include the TOP component to the `GLOBAL_QCO` config in the cfgs/work_cfgs.txt file, where the configs to be compile are listed.  Now both `GLOBAL_QCO` and `GLOBAL_QCO_MEDUSA` are compiled when running `./setup`.

I've modified that in the branch linked to this issue.   

Have a look, but i think the issue is closed, and the fix can be safely merged into main.

Julien.

**Comment by atb299** [comment] 2024-02-19 12:06
How do you run age tracers without TOP? 

I was going to take a look myself before assigning it to you, but it seems you found the issue anyway... 

I think it is something to do with the modifications to makenemo. Maybe it just needs an "if MEDUSA..." or something like that?

**Comment by jupalm** [comment] 2024-02-19 12:22
> How do you run age tracers without TOP?


Well you can't,   
the problem is that MEDUSA is checked-out, but the modified NEMO-trc files are only in the `GLOBAL_QCO_MEDUSA` cfgs.  So if you include `TOP` in your `GLOBAL_QCO` cfgs that doesn't include these modified trc subroutines, it won't compile.

The easiest way for your to run the Age tracer would be to  
* use the `GLOBAL_QCO_MEDUSA` cfgs 
* make sure the age namelists are in your running dir, 
* make sure your xml files include not medusa outputs but the Age tracer output
* modify the namelist_top_cfg to not run MEDUSA but the age tracer : 
   ```
&namtrc          !   tracers definition
!-----------------------------------------------------------------------
   jp_bgc        =  0           !  Number of passive tracers of the BGC model
   !
   ln_medusa = .false. ! Run MEDUSA BGC model
   ln_pisces     =  .false.     !  Run PISCES BGC model 
   ln_my_trc     =  .false.     !  Run MY_TRC BGC model
   ln_age        =  .true.     !  Run the sea water age tracer
   ln_cfc11      =  .false.     !  Run the CFC11 passive tracer
   ln_cfc12      =  .false.     !  Run the CFC12 passive tracer
   ln_sf6        =  .false.     !  Run the SF6 passive tracer
   ln_c14        =  .false.     !  Run the Radiocarbon passive tracer
   !
   ```
That should be enough to run NEMO-Age without MEDUSA.

**Closed as completed** 2024-02-21 15:01 UTC
